# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: /go/src/github.com/ericjaystevens/agilespud
    steps:
      - checkout

      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: go build -o main main.go
      - store_artifacts:
          path: main
      - run: mkdir bin
      - run: zip bin/main.zip main
      - persist_to_workspace:
        root: bin
  deploy:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - attach_workspace:
        # Must be absolute path or relative path from working_directory
        at: /tmp/bin

      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build  